spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false&user=root&password=sandeep
    # username: root